package pixiv

const USER_DETAIL = "v1/user/detail"
const USER_AUTHOR = "v1/user/illusts"
const BOOKMARKS = "v1/user/bookmarks/illust"
const FOLLOW = "v2/illust/follow"
const COMMENTS = "v1/illust/comments"
const DETAIL = "v1/illust/detail"
const RELATED = "v2/illust/related"
const RECOMMENDED = "v1/illust/recommended"
const RECOMMENDED_NO_LOGIN = "v1/illust/recommended-nologin"
const RANKING = "v1/illust/ranking"
const SEARCH = "v1/search/illust"
const ADD = "v1/illust/comment/add"
const BOOKMARK_ADD = "v2/illust/bookmark/add"
const BOOKMARK_DELETE = "v1/illust/bookmark/delete"
