package pixiv

const API_BASE = "https://app-api.pixiv.net/"
const WEB_BASE = "https://www.pixiv.net"
const WEB_ARTICLE = "ajax/showcase/article"
const USER = "v1/user/"
const USER_DETAIL = "v1/user/detail"
const USER_AUTHOR = "v1/user/illusts"
const USER_FOLLOW = "v1/user/follow/"
const USER_MYPIXIV = "/v1/user/mypixiv"
const USER_LIST = "v2/user/list"
const BOOKMARKS = "v1/user/bookmarks/illust"
const FOLLOW = "v2/illust/follow"
const COMMENTS = "v1/illust/comments"
const DETAIL = "v1/illust/detail"
const RELATED = "v2/illust/related"
const RECOMMENDED = "v1/illust/recommended"
const RECOMMENDED_NO_LOGIN = "v1/illust/recommended-nologin"
const RANKING = "v1/illust/ranking"
const SEARCH = "v1/search/illust"
const ADD = "v1/illust/comment/add"
const METADATA = "v1/ugoira/metadata"
const BOOKMARK_ADD = "v2/illust/bookmark/add"
const BOOKMARK_DELETE = "v1/illust/bookmark/delete"
const BOOKMARK_DETAIL = "v2/illust/bookmark/detail"
const BOOKMARK_TAG = "v1/user/bookmark-tags/illust"
const TRENDING_TAGS = "v1/trending-tags/illust"
